version: '3'

services:
  mongo_db: 
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  app:
    build: .
    ports: 
      - 9000:5000
    environment: 
      APP_NAME: LearnDocker
      PORT: 5000
      DB_URL: mongodb://localhost:27017/dockerlearn
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
